// <auto-generated />
namespace SpadCompanyPanel.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class init16 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init16));
        
        string IMigrationMetadata.Id
        {
            get { return "202108020550455_init16"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
